### ISSUE TITLE
Error while running longhorn-monitoring version 1.0.1

### ISSUE THREAD

**Issue by IMAN-NAMJOOYAN** [SomeBlackMagic/helm-charts#1]
Hi 

I have an error while running "helm install my-longhorn-monitoring someblackmagic/longhorn-monitoring --version 1.0.1"

**Error: INSTALLATION FAILED: template: longhorn-monitoring/templates/prometheus/servicemonitor.yaml:1:8: executing "longhorn-monitoring/templates/prometheus/servicemonitor.yaml" at <$.Values.serviceMonitor.enabled>: enabled is not a method but has arguments**

Kubernetes version: v1.25.5
Longhorn Version: v1.4.0

Thanks

**Comment by wirwolf** [comment]
Hello. Thanks for your issue. I will try to check this issue this week

**Comment by wirwolf** [comment]
Fixed in version 1.0.3
